# Generated by Django 2.2 on 2019-04-12 08:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ISBN', models.CharField(max_length=30)),
                ('BookName', models.CharField(max_length=250)),
                ('FrontPage', models.CharField(default='static/no_frontpage.png', max_length=400)),
                ('Author', models.CharField(default='未知', max_length=100)),
                ('Translator', models.CharField(default='无', max_length=100)),
                ('Publisher', models.CharField(default='未知', max_length=100)),
                ('Quantity', models.IntegerField(default=1)),
                ('Introduction', models.TextField()),
                ('Devoter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DevoteRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('DevoteTime', models.DateTimeField(auto_now_add=True)),
                ('Book', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('User', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BorrowRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('BeginTime', models.DateTimeField(auto_now_add=True)),
                ('finished', models.BooleanField(default=False)),
                ('BookBorrowed', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='books.Book')),
                ('Borrower', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
