# Generated by Django 2.2 on 2019-04-13 11:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Devoter',
        ),
        migrations.AddField(
            model_name='book',
            name='DatePublished',
            field=models.DateField(default='1900-01-01'),
        ),
        migrations.AddField(
            model_name='book',
            name='DateRegistered',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='book',
            name='Author',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='Publisher',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.AlterField(
            model_name='book',
            name='Translator',
            field=models.CharField(default='unknown', max_length=100),
        ),
        migrations.DeleteModel(
            name='DevoteRecord',
        ),
    ]
