# Generated by Django 2.2 on 2019-04-13 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0002_auto_20190413_1311'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='Translator',
        ),
        migrations.AlterField(
            model_name='book',
            name='DatePublished',
            field=models.DateField(default='1900-01-01'),
        ),
    ]
