# Generated by Django 2.2 on 2019-04-13 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0003_auto_20190413_1317'),
    ]

    operations = [
        migrations.AddField(
            model_name='borrowrecord',
            name='EndTime',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='book',
            name='DatePublished',
            field=models.DateField(blank=True, null=True),
        ),
    ]
