# Generated by Django 2.2 on 2019-05-06 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0006_auto_20190503_1048'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[(11, 'Tokyo'), (12, 'Osaka'), (13, 'Fukuoka'), (21, 'Berlin'), (22, 'Hamburg')], default=21, max_length=2),
        ),
    ]
