# Generated by Django 2.2 on 2019-05-06 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_book_category'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='category',
            new_name='location',
        ),
    ]
