# Generated by Django 2.2 on 2019-05-06 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_auto_20190506_1804'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='location',
            field=models.IntegerField(choices=[(11, 'Tokyo'), (12, 'Osaka'), (13, 'Fukuoka'), (21, 'Berlin'), (22, 'Hamburg')], default=21),
        ),
    ]
